version: '3'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./:/var/www
            - ./iac/nginx/conf.d:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: './iac/php/Dockerfile'
        container_name: php
        volumes:
            - ./:/var/www
            - ./iac/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    db:
        image: mysql:5.7.22
        container_name: db
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: banco
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - dbdata:/var/lib/mysql/
            - ./iac/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
