User:
  type: object
  config:
    description: "User"
    fields:
      id:
        type: "Int"
        description: "User id"
      name:
        type: "String"
        description: "User name"
      email:
        type: "String"
        description: "User email"
      accounts:
        type: "[Account]"
        description: "User accounts"
        resolve: "@=value.getAccounts()"
